const { EmbedBuilder } = require("discord.js");

module.exports.HelpEmbed = new EmbedBuilder()
    .setTitle("Lifter's Log Help")
    .setDescription("Here is how to get started with using the bot.")
    .addFields({ name: "/log [movement] [weight] [reps] [sets] [date]", value: "Use this command and pick a [movement] from the list along with the [weight] you used and the [reps] you did. You can also log multiple [sets] at a time if they were exactly the same.\n- If an exercise uses dumbbells, log the weight of **one dumbbell**.\n- If an exercise is a body weight exercise, log the **additional** weight if any.\n- Split exercises such as Bulgarian Split Squats and single arm exercises assume you are logging one arm/leg at a time.\n- If you need to log for a previous day use [date] otherwise sets are automatically logged on the current day." })
    .addFields({ name: "/cardio [movement] [time] [date] [note] [distance]", value: "Use this command to log a cardio [movement]\n- [time] is the only required field, but you may add [distance] (in miles) and any additional [note]s.\n- Cardio is a work in progess and can only be displayed with /summary right now." })
    .addFields({ name: "/undo [sets]", value: "Use this command to undo the last logged set, or [sets], if you made a mistake." })
    .addFields({ name: "/repeat [sets] [weight] [reps]", value: "Use this command to repeat the last logged movement [sets] times, leaving [weight] and/or [reps] blank uses the previous set's numbers." })
    .addFields({ name: "/profile [user]", value: "Use this command to view information about your profile such as your level, current xp, body weight, days skipped, skip streak, and programmed rest days.\n- Adding a [user] allows you to view someone elses profile." })
    .addFields({ name: "/history [date]", value: "Use this command to view your history of logged sets.\n- Entering a [date] will give you the history starting from that date." })
    .addFields({ name: "/findlast [movement]", value: "Use this command to find the last occurence of a specified [movement]."})
    .addFields({ name: "/stats [movement]", value: "Use this command to see statistics about the specified [movement] you have logged." })
    .addFields({ name: "/summary [date]", value: "Use this command to get a summary for a given [date] (Current day by default)\n- Scores are based on your set average from the past 60 days." })
    .addFields({ name: "/graph [movement] [type] [time]", value: "Use this command to generate a [type] of graph for a [movement] in a certain amount of [time]." })
    .addFields({ name: "/restday [day]", value: "Use this command to save/unsave a programmed rest day." })
    .addFields({ name: "/bodyweight [weight]", value: "Use this command to register your body weight.\n- **NOTE:** If you do not register a body weight, assisted exercises and bodyweight exercises will not give you xp." })
    .addFields({ name: "/squat /bench /deadlift", value: "Use these commands to register your squat, bench, and deadlift one rep max." })
    .addFields({ name: "/label [label]", value: "Use this command to label the current day."})
    .addFields({ name: "/leaderboard [stat]", value: "Use this command to display a global leaderboard of all users sorted by specified [stat]." })
    .setFooter({ text: "Created by Bryan." });